### ISSUE TITLE
{random} lead always to "hello" in voice channel format

### ISSUE THREAD

**Issue by LeiRoF** [ZRunner/ZBot#19]
![image](https://user-images.githubusercontent.com/12165342/177538823-10017747-8628-450b-80c6-9290adf2f6cb.png)

![image](https://user-images.githubusercontent.com/12165342/177538841-80ca496c-4c61-451a-9b77-9a2bfb6620b5.png)

**Comment by ZRunner** [comment]
Yeah, this happens when the random names API is down and the bot can’t reach it.

If you have a better idea, feel free to share it!

**Comment by LeiRoF** [comment]
I have few ideas about that:

1) add the {number} parameter that allow to put an unique number in every channel
2) add {user} that is replace by the name of the user
3) If you want, after I finished what I'm currently doing, I can try to code a little function that generate a random word according to frequency of letter apparition (I always wanted to make this little program haha)

Parameter associated to a themes:
4) add {minecraft_entity} that take one of the entity [listed here](https://github.com/PixiGeko/Minecraft-generated-data/blob/master/1.19/releases/1.19/data/custom/universal_tags/all_entity_type.json)
5) add back the {astrix} parameter by generating a liste based on [this page](https://www.asterix.com/les-personnages/) (maybe you can ask to Raph, he loves to webscrap websites 😂)

**Comment by ZRunner** [comment]
Good enough for now I guess?
![Capture d’écran 2022-07-08 à 23 07 17](https://user-images.githubusercontent.com/30912430/178070487-1c8987e0-31b0-4e1e-92b5-02470a0941d5.png)

(FYI, {user} is already a valid variable, I'll add it in the documentation for the next release)

**Comment by LeiRoF** [comment]
Hahaha, yes, good enoguh xD

**Comment by ZRunner** [comment]
About the random names:
- their API is somehow protected by Cloudflare, which returns a HTML protection/verification page for whatever reason they have. So the JSON content is blocked from my server
- I tried to contact them, but their contact form doesn't work and returns a 400 HTTP error

So rn I have no idea how I'm going to fix this, or even if it's possible. I will close this ticket and try to find a solution for the next update.
