### ISSUE TITLE
[improvement] change all feeds settings in one time

### ISSUE THREAD

**Issue by Albirew** [ZRunner/ZBot#7]
Is it possible to change all feeds in one time instead of a per-feed basis when chosen flow ID is a special char(s?) (like *, !, ?, or anything you see fit, like !all or ?mass? )
For instance, with moving feeds, adding a role to ping, use_embed, or changing feeds text.
something like that: `!rss move ! #newChannel`

**Comment by ZRunner** [comment]
Yup, that would definitively be something interesting to get.
My plan for now is to use the new Discord "Select" menu, which should be able to handle multiple selections at the same time. I'll keep your idea in my list, thanks!

**Comment by ZRunner** [comment]
Implemented in 1cbfeda97599895707269ab77cf9a2add30934ec for move and delete (will be available in v4.0)

I don't think there's a point to allow people to mass-edit mentions or text template, let me know if you think otherwise.

**Comment by Albirew** [comment]
In my use (ping specific group when a new RSS feed for selected category is out), mass edit mentions is not much useful and I cannot come up with a good example (maybe for new people setting the bot for the first time, maybe?).

Text template ass edit may be a thing (not that I spent much time in setting each, tho).
That, or setting a default value for new and unset feeds. Actually, trice (nothing, mass edit or default setting) are fine.

**Comment by ZRunner** [comment]
Resolved in [dca2620](https://github.com/ZRunner/ZBot/commit/dca26205e87a9b0ae715c8ed66158fcdbabcccf4)
